import { Bird, Flame, Footprints, Leaf, Droplet, WavesIcon, TrainFront, Cloud, TreePine, Bug, Moon, Speaker, Wind, Coffee, Waves } from "lucide-react";

export const allAmbientSounds = [
  { name: "Blackbird", url: "/sound/birdblackbird.ogg", category: "Birds", icon: Bird },
  { name: "Crow", url: "/sound/birdcrow.ogg", category: "Birds", icon: Bird },
  { name: "Nightingale", url: "/sound/birdnightingale.ogg", category: "Birds", icon: Bird },
  { name: "Calm Fire", url: "/sound/firecalm.ogg", category: "Fire", icon: Flame },
  { name: "Fire Crackling", url: "/sound/firecrackling.ogg", category: "Fire", icon: Flame },
  { name: "Gravel Footsteps", url: "/sound/footstepsgravel.ogg", category: "Footsteps", icon: Footprints },
  { name: "Eerie Forest", url: "/sound/foresteerie.ogg", category: "Forest", icon: TreePine },
  { name: "Evening Forest", url: "/sound/forestevening.ogg", category: "Forest", icon: TreePine },
  { name: "Frog Chorus", url: "/sound/frogchorus.ogg", category: "Frogs", icon: Bug },
  { name: "Cricket Frog", url: "/sound/frogcricket.ogg", category: "Frogs", icon: Bug },
  { name: "Natterjack Frog", url: "/sound/frognatterjack.ogg", category: "Frogs", icon: Bug },
  { name: "Wood Frog", url: "/sound/frogwood.ogg", category: "Frogs", icon: Bug },
  { name: "Rustling Leaves", url: "/sound/leaves.ogg", category: "Leaves", icon: Leaf },
  { name: "Night Meadow", url: "/sound/nightmeadow.ogg", category: "Night", icon: Moon },
  { name: "Night Suburban", url: "/sound/nightsuburban.ogg", category: "Night", icon: Moon },
  { name: "Dense Rain", url: "/sound/raindense.ogg", category: "Rain", icon: Droplet },
  { name: "Rain Dripping", url: "/sound/raindripping.ogg", category: "Rain", icon: Droplet },
  { name: "Rain Gutter", url: "/sound/raingutter.ogg", category: "Rain", icon: Droplet },
  { name: "Rain Porch", url: "/sound/rainporch.ogg", category: "Rain", icon: Droplet },
  { name: "Rain Shack", url: "/sound/rainshack.ogg", category: "Rain", icon: Droplet },
  { name: "English Restaurant", url: "/sound/restaurantenglish.ogg", category: "Cafe", icon: Coffee },
  { name: "Calm River", url: "/sound/rivercalm.ogg", category: "River", icon: WavesIcon },
  { name: "Strong River", url: "/sound/riverstrong.ogg", category: "River", icon: WavesIcon },
  { name: "Thunder", url: "/sound/thunder.ogg", category: "Weather", icon: Cloud },
  { name: "Fast Train", url: "/sound/trainfast.ogg", category: "City", icon: TrainFront },
  { name: "Slow Train", url: "/sound/trainslow.ogg", category: "City", icon: TrainFront },
  { name: "Beach Waves", url: "/sound/wavesbeach.ogg", category: "Ocean", icon: Waves },
  { name: "Slow Waves", url: "/sound/wavesslow.ogg", category: "Ocean", icon: Waves },
  { name: "Howling Wind", url: "/sound/windhowling.ogg", category: "Wind", icon: Wind },
  { name: "Steady Wind", url: "/sound/windsteady.ogg", category: "Wind", icon: Wind },
  { name: "White Noise", url: "/sound/noisewhite.ogg", category: "Noise", icon: Speaker },
];