"use client";

import type { Metadata } from "next/types";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SessionContextProvider } from "@/integrations/supabase/auth";
import { WidgetProvider } from "@/components/widget/widget-context";
import { useState } from "react";
import { DndWrapper } from "@/components/dnd-wrapper";

const inter = Inter({ subsets: ["latin"] });

// Metadata can stay server-side, but the component needs "use client"
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarDocked, setIsSidebarDocked] = useState(true);
  const [sidebarPosition, setSidebarPosition] = useState({ x: 0, y: 64 }); // Initial docked position (top-16)

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <SessionContextProvider>
              <WidgetProvider>
                <DndWrapper
                  isSidebarDocked={isSidebarDocked}
                  onToggleDock={() => setIsSidebarDocked(prev => !prev)}
                  sidebarPosition={sidebarPosition}
                  onSidebarPositionChange={setSidebarPosition}
                >
                  {children}
                </DndWrapper>
              </WidgetProvider>
            </SessionContextProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}