// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mrdupsekghsnbooyrdmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yZHVwc2VrZ2hzbmJvb3lyZG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDM0ODYsImV4cCI6MjA2Njg3OTQ4Nn0.enmXsshBH69-oLcOdrMbUxpwtHq5f5wjYA6k-08BU-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);